firstname = input("Enter your first name: ")
print("My first name is", firstname)
age = int(input("How old are you?: "))
print()
print("I am", age, "years old")
print()
height = float(input("Enter your height: "))
print("I am", height, "in")
print("----End----")
print("Thank you for your feedback")